apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: el-practicetest
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: trigger-template-simple-httpd